apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
type: Opaque
stringData:
  AWS_SQS_URL: ""
  SQS_ENDPOINT: ""
  DYNAMODB_ENDPOINT: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""

