apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/part-of: togglemaster
type: Opaque
stringData:
  REDIS_URL: ""
  AWS_SQS_URL: ""
  SQS_ENDPOINT: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""

